export {
  DomainCommandError,
  applyCommand,
  applyCommands,
  applyCommandToHistory,
  createCommandHistory,
  executeCommand,
  redo,
  redoCommand,
  undo,
  undoCommand,
  type CommandHistory,
  type CommandHistoryEntry,
  type CommandResult,
  type AddViewItemCommand,
  type CreateElementCommand,
  type CreateViewCommand,
  type CreateRelationshipCommand,
  type DeepReadonly,
  type DeleteElementCommand,
  type DeleteRelationshipCommand,
  type DeleteViewCommand,
  type DomainCommand,
  type DomainCommandErrorCode,
  type ElementChanges,
  type MoveViewItemsCommand,
  type RelationshipChanges,
  type RemoveViewItemCommand,
  type ReparentElementCommand,
  type ReadonlyPatch,
  type ReadonlyProject,
  type UpdateElementCommand,
  type UpdateRelationshipCommand,
  type UpdateViewCommand,
  type ViewChanges,
  type ViewItemMove,
  type ViewPlacement,
} from './commands.js';

export {
  CameraBookmarkIdSchema,
  CameraBookmarkSchema,
  ElementIdSchema,
  ElementKindSchema,
  ElementSchema,
  ExternalReferenceSchema,
  JsonValueSchema,
  LIMITS,
  Placement2DSchema,
  ProjectIdSchema,
  ProjectSchema,
  PropertiesSchema,
  RelationshipIdSchema,
  RelationshipSchema,
  SCHEMA_VERSION,
  ThreeDPolicySchema,
  Vector3Schema,
  ViewIdSchema,
  ViewItemIdSchema,
  ViewAnnotationSchema,
  ViewItemSchema,
  ViewSchema,
  type CameraBookmarkId,
  type CameraBookmarkInput,
  type CameraBookmark,
  type Component,
  type Container,
  type Element,
  type ElementId,
  type ElementInput,
  type ElementKind,
  type ExternalReference,
  type JsonValue,
  type Placement2D,
  type Placement2DInput,
  type Person,
  type Project,
  type ProjectId,
  type ProjectInput,
  type Relationship,
  type RelationshipId,
  type RelationshipInput,
  type RelationshipInteraction,
  type SoftwareSystem,
  type ThreeDPolicy,
  type Vector3,
  type View,
  type ViewId,
  type ViewAnnotation,
  type ViewInput,
  type ViewItem,
  type ViewItemId,
  type ViewItemInput,
  type ViewType,
} from './schema.js';
